#!/usr/bin/with-contenv bash

if [ -f "/etc/gcs-key.json" ]; then

  mkdir -p /mnt/gcs
  chown -R abc:abc \
    /etc/gcs-key.json
    /mnt/gcs

  echo "$BUCKET /mnt/gcs gcsfuse rw,user,noauto,key_file=/etc/gcs-key.json" >> /etc/fstab
  s6-setuidgid abc mount.gcsfuse "$BUCKET" "/mnt/gcs" || exit 1
else
  echo "Fatal: No Service Account key found. Please follow the instructions to get your key and pass it to the container."
  exit 1
fi
